services:
  db:
    image: mariadb
    ports: # !!! REMOVE IN PRODUCTION !!!
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-u", "${DB_USER}", "-p${DB_PASS}"]
      interval: 1s
      timeout: 5s
      retries: 15

  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    environment:
      DB_SERVER: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: