syntax = "proto3";
import "user.proto";
import "product.proto";

option csharp_namespace = "Protos.Loan";

package loan;

service Loans {
  rpc Page (LoanPageRequest) returns (LoanPageResponse);
  rpc Get (LoanGetRequest) returns (LoanGetResponse);
  rpc Create (LoanCreateRequest) returns (LoanCreateResponse);
  rpc Modify (LoanModifyRequest) returns (LoanModifyResponse);
  rpc Delete (LoanDeleteRequest) returns (LoanDeleteResponse);
}

// Meta
message MetaLoan {
  int32 id = 1;
  user.MetaUser user = 2;
  user.MetaUser lender = 3;
  int64 LoanedAt = 4;
  int64 DueAt = 5;
  optional int64 ReturnedAt = 6;
  repeated MetaLoanProduct products = 7;
}

message MetaLoanProduct {
  int32 amount = 1;
  bool returned = 2;
  int32 product_id = 3;
  optional product.MetaProduct product = 4;
}

// Page
message LoanPageRequest {
  int32 page = 1;
  int32 page_size = 2;
}

message LoanPageResponse {
  repeated MetaLoan loans = 1;
}

// Get
message LoanGetRequest {
  int32 id = 1;
}

message LoanGetResponse {
  optional MetaLoan loan = 1;
}

// Create
message LoanCreateRequest {
  int32 user_id = 1;
  int64 DueAt = 2;
  repeated MetaLoanProduct products = 3;
}

message LoanCreateResponse {
  bool success = 1;
}

// Modify
message LoanModifyRequest {
  int32 id = 1;
  repeated MetaLoanProduct products = 2;
}

message LoanModifyResponse {
  bool success = 1;
}

// Delete
message LoanDeleteRequest {
  int32 id = 1;
}

message LoanDeleteResponse {
  bool response = 1;
}
