syntax = "proto3";
import "user.proto";
import "product.proto";

option csharp_namespace = "Protos.Loan";

// Meta
message MetaLoan {
  int32 id = 1;
  user.MetaUser user = 2;
  user.MetaUser lender = 3;
  int64 LoanedAt = 4;
  int64 DueAt = 5;
  int64 ReturnedAt = 6;
  repeated MetaLoanProduct products = 7;
}

message MetaLoanProduct {
  int32 id = 1;
  int32 amount = 2;
  bool returned = 3;
  product.MetaProduct product = 4;
}

// Page
message LoanPageRequest {
  int32 page = 1;
  int32 page_size = 2;
}

message LoanPageResponse {
  repeated MetaLoan loans = 1;
}

// Get
message GetLoanRequest {
  int32 id = 1;
}

message GetLoanResponse {
  MetaLoan loan = 1;
}

// Create
message CreateLoanRequest {
  user.MetaUser user = 1;
  user.MetaUser lender = 2;
  int64 LoanedAt = 3;
  int64 DueAt = 4;
  int64 ReturnedAt = 5;
  repeated MetaLoanProduct products = 6;
}

message CreateLoanResponse {
  bool success = 1;
}

// Modify
message ModifyLoanRequest {
  int32 id = 1;
  optional user.MetaUser user = 2;
  optional user.MetaUser lender = 3;
  optional int64 LoanedAt = 4;
  optional int64 DueAt = 5;
  optional int64 ReturnedAt = 6;
  repeated MetaLoanProduct products = 7;
}

message ModifyLoanResponse {
  bool success = 1;
}

// Delete
message DeleteLoanRequest {
  int32 id = 1;
}

message DeleteLoanResponse {
  bool response = 1;
}
