syntax = "proto3";

option csharp_namespace = "Protos.Product";

package product;

service Products {
  rpc Page (ProductPageRequest) returns (ProductPageResponse);
  rpc Get (ProductGetRequest) returns (ProductGetResponse);
  rpc Create (ProductCreateRequest) returns (ProductCreateResponse);
  rpc Modify (ProductModifyRequest) returns (ProductModifyResponse);
  rpc Delete (ProductDeleteRequest) returns (ProductDeleteResponse);
  rpc Image (ProductImageRequest) returns (stream ProductImageResponse);
  rpc Role (ProductRoleRequest) returns (ProductRoleResponse);
  rpc Category (ProductCategoryRequest) returns (ProductCategoryResponse);
  rpc LenderRole (ProductLenderRoleRequest) returns (ProductLenderRoleResponse);
}

// Meta
message MetaProduct {
  int32 id = 1;
  string name = 2;
  string description = 3;
  Category category = 4;
  Role role = 5;
  string image = 6;
  repeated Role roles = 7;
}

message Role {
  int32 id = 1;
  string name = 2;
}

message Category {
  int32 id = 1;
  string name = 2;
}

// Page
message ProductPageRequest {
  int32 page = 1;
  int32 page_size = 2;
}

message ProductPageResponse {
  repeated MetaProduct products = 1;
}

// Get
message ProductGetRequest {
  int32 id = 1;
}

message ProductGetResponse {
  MetaProduct product = 1;
}

// Create
message ProductCreateRequest {
  string name = 1;
  string description = 2;
  Category category = 3;
  int32 role_id = 4;
  bytes image = 5;
  repeated int32 role_ids = 6;
}

message ProductCreateResponse {
  bool success = 1;
}

// Modify
message ProductModifyRequest {
  int32 id = 1;

  optional string name = 2;
  optional string description = 3;
  optional Category category = 4;
  optional int32 role_id = 5;
  optional bytes image = 6;
  repeated int32 role_ids = 7;
}

message ProductModifyResponse {
  bool success = 1;
}

// Delete
message ProductDeleteRequest {
  int32 id = 1;
}

message ProductDeleteResponse {
  bool success = 1;
}

// Image
message ProductImageRequest {
  string name = 1;
}

message ProductImageResponse {
  bytes raw = 1;
  string extension = 2;
}

// Role
message ProductRoleRequest {
}

message ProductRoleResponse {
  repeated Role Roles = 1;
}

// Category
message ProductCategoryRequest {
}

message ProductCategoryResponse {
  repeated Category categories = 1;
}

message ProductLenderRoleRequest {
}

message ProductLenderRoleResponse {
  repeated Role Roles = 1;
}
