syntax = "proto3";
import "google/protobuf/wrappers.proto";
option csharp_namespace = "Shared";

package user;

service Products {
  rpc Page (ProductPageRequest) returns (ProductPageResponse);

  rpc Get (ProductGetRequest) returns (ProductGetResponse);

  rpc Create (stream ProductCreateRequest) returns (ProductCreateResponse);

  rpc Modify (ProductModifyRequest) returns (ProductModifyResponse);

  rpc Delete (ProductDeleteRequest) returns (ProductDeleteResponse);

  rpc GetImage (ProductImageRequest) returns (stream ImageData);
}

// Meta object
message MetaProduct {
  int32 id = 1;
  string name = 2;
  string category = 3;
  string description = 4;
  int32 amount = 5;
  string image = 6;
}

message ImageData {
  bytes raw = 1;
  string extension = 2;
}

// Page
message ProductPageRequest {
  int32 page = 1;
  int32 page_size = 2;
}

message ProductPageResponse {
  repeated MetaProduct products = 1;
}

// Get
message ProductGetRequest {
  int32 id = 1;
}

message ProductGetResponse {
  MetaProduct product = 1;
}

// Create
message ProductCreateRequest {
  string name = 2;
  string category = 3;
  string description = 4;
  google.protobuf.Int32Value amount = 5;
  bytes image = 6;
}

message ProductCreateResponse {
  bool success = 1;
}

// Modify
message ProductModifyRequest {
  int32 id = 1;
    optional string name = 2;
    optional string category = 3;
    optional string description = 4;
    optional int32 amount = 5;
    optional bytes image = 6;
}

message ProductModifyResponse {
  bool success = 1;
}

// Delete
message ProductDeleteRequest {
  int32 id = 1;
}

message ProductDeleteResponse {
  bool success = 1;
}

// Image
message ProductImageRequest {
  string name = 1;
}

message ProductImageResponse {
  bool success = 1;
}
