syntax = "proto3";

option csharp_namespace = "Protos.User";

package user;

service Users {
  rpc Page (UserPageRequest) returns (UserPageResponse);
  rpc Get (UserGetRequest) returns (UserGetResponse);
  rpc Create (UserCreateRequest) returns (UserCreateResponse);
  rpc Modify (UserModifyRequest) returns (UserModifyResponse);
  rpc Delete (UserDeleteRequest) returns (UserDeleteResponse);
}

// Meta
message MetaUser {
  int32 id = 1;
  bytes card_id = 2;
  string first_name = 3;
  string last_name = 4;
  string email = 5;
  int32 role_id = 6;
  int32 number = 7;
  bool is_blocked = 8;
}

// Page
message UserPageRequest {
  int32 page = 1;
  int32 page_size = 2;
}

message UserPageResponse {
  repeated MetaUser users = 1;
}

// Get
message UserGetRequest {
  int32 id = 1;
}

message UserGetResponse {
  MetaUser user = 1;
}

// Create
message UserCreateRequest {
  bytes card_id = 2;
  string first_name = 3;
  string last_name = 4;
  string email = 5;
  int32 role_id = 6;
  int32 number = 7;
  bool is_blocked = 8;
}

message UserCreateResponse {
  bool success = 1;
}

// Modify
message UserModifyRequest {
  int32 id = 1;

  optional bytes card_id = 2;
  optional string first_name = 3;
  optional string last_name = 4;
  optional string email = 5;
  optional int32 role_id = 6;
  int32 number = 7;
  bool is_blocked = 8;
}

message UserModifyResponse {
  bool success = 1;
}

// Delete
message UserDeleteRequest {
  int32 id = 1;
}

message UserDeleteResponse {
  bool success = 1;
}