syntax = "proto3";
import "product.proto";

option csharp_namespace = "Protos.User";

package user;

service Users {
  rpc Page (UserPageRequest) returns (UserPageResponse);
  rpc Get (UserGetRequest) returns (UserGetResponse);
  rpc Create (UserCreateRequest) returns (UserCreateResponse);
  rpc Modify (UserModifyRequest) returns (UserModifyResponse);
  rpc Delete (UserDeleteRequest) returns (UserDeleteResponse);
  rpc LenderScan (UserLenderScanRequest) returns (UserLenderScanResponse);
  rpc LenderPage (UserLenderPageRequest) returns (UserLenderPageResponse);
}

// Meta
message MetaUser {
  int32 id = 1;
  bytes card_id = 2;
  string first_name = 3;
  string last_name = 4;
  string email = 5;
  int32 number = 6;
  repeated product.Role roles = 7;
}

// Page
message UserPageRequest {
  int32 page = 1;
  int32 page_size = 2;
}

message UserPageResponse {
  repeated MetaUser users = 1;
}

// Get
message UserGetRequest {
  int32 id = 1;
}

message UserGetResponse {
  MetaUser user = 1;
}

// Create
message UserCreateRequest {
  bytes card_id = 2;
  string first_name = 3;
  string last_name = 4;
  string email = 5;
  int32 number = 6;
  repeated int32 role_ids = 7;
}

message UserCreateResponse {
  bool success = 1;
}

// Modify
message UserModifyRequest {
  int32 id = 1;

  optional bytes card_id = 2;
  optional string first_name = 3;
  optional string last_name = 4;
  optional string email = 5;
  optional int32 number = 6;
  repeated int32 role_ids = 7;
}

message UserModifyResponse {
  bool success = 1;
}

// Delete
message UserDeleteRequest {
  int32 id = 1;
}

message UserDeleteResponse {
  bool success = 1;
}

// Info by card

message UserLenderScanRequest {
  bytes card_id = 1;
}

message UserLenderScanResponse {
  optional string email = 1;
  optional string name = 2;
}

// LenderPage

message UserLenderPageRequest {
  int32 page = 1;
  int32 page_size = 2;
}

message UserLenderPageResponse {
  repeated MetaUser users = 1;
}
