syntax = "proto3";

option csharp_namespace = "Shared";

package user;

service Users {
  rpc Get (GetRequest) returns (GetResponse);

  rpc Create (CreateRequest) returns (CreateResponse);

  rpc Modify (ModifyRequest) returns (ModifyResponse);

  rpc Delete (DeleteRequest) returns (DeleteResponse);
}

// Meta object
message MetaUser {
  bytes id = 1; // BINARY(7)
  string email = 2;
  string name = 3;
  uint32 number = 4;
  bool staff = 5;
}

// Get
message GetRequest {
  int32 page = 1;
  int32 page_size = 2;
}

message GetResponse {
  repeated MetaUser users = 1;
}

// Create
message CreateRequest {
  bytes id = 1;
  string email = 2;
  string name = 3;
  uint32 number = 4;
  bool staff = 5;
}

message CreateResponse {
  bool success = 1;
}

// Modify
message ModifyRequest {
  bytes id = 1;
    optional string email = 2;
    optional string name = 3;
    optional uint32 number = 4;
    optional bool staff = 5;
}

message ModifyResponse {
  MetaUser user = 1;
}

// Delete
message DeleteRequest {
  bytes id = 1;
}

message DeleteResponse {
  bool success = 1;
}
